### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by dominikkerkow** [a1development/ioBroker.boschindego#101]
Aktuell läuft der Adapter kurze Zeit, dann fangen die Error Meldungen an. Manchmal habe ich den Verdacht, wenn der Mäher bei was hängen bleibt, geht es los, aber auch so kommen die Fehler.
Ich habe zwei verschiedene Indego und somit zwei Adapter installiert. Beide mit demselben Verhalten.

Siehe Infos aus dem Protokoll:

`
boschindego.0 | 2022-04-29 16:58:39.964 | warn | Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
-- | -- | -- | --
boschindego.0 | 2022-04-29 16:58:39.959 | error | adapter disabled
boschindego.0 | 2022-04-29 16:58:08.818 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
boschindego.0 | 2022-04-29 16:58:08.817 | info | terminating
boschindego.0 | 2022-04-29 16:58:08.815 | error | error in machine request: Error: Request failed with status code 429
boschindego.0 | 2022-04-29 16:58:08.810 | error | Request failed with status code 429
boschindego.0 | 2022-04-29 16:58:08.809 | error | Error: Request failed with status code 429 at createError (/opt/iobroker/node_modules/iobroker.boschindego/node_modules/axios/lib/core/createError.js:16:15) at settle (/opt/iobroker/node_modules/iobroker.boschindego/node_modules/axios/lib/core/settle.js:17:12) at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/iobroker.boschindego/node_modules/axios/lib/adapters/http.js:269:11) at IncomingMessage.emit (events.js:412:35) at endReadableNT (internal/streams/readable.js:1334:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)
boschindego.0 | 2022-04-29 16:58:08.808 | error | unhandled promise rejection: Request failed with status code 429
boschindego.0 | 2022-04-29 16:58:08.807 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
boschindego.0 | 2022-04-29 16:58:08.806 | error | error in alerts request: Error: Request failed with status code 429
boschindego.0 | 2022-04-29 16:58:05.604 | info | connect ok
boschindego.0 | 2022-04-29 16:58:05.241 | info | connect
boschindego.0 | 2022-04-29 16:57:48.301 | error | connection error - credentials wrong or no network?
boschindego.0 | 2022-04-29 16:57:45.242 | info | connect
boschindego.0 | 2022-04-29 16:57:35.354 | error | connection error - credentials wrong or no network?
boschindego.0 | 2022-04-29 16:57:32.293 | info | connect
boschindego.0 | 2022-04-29 16:57:29.229 | info | connect ok
boschindego.0 | 2022-04-29 16:57:28.700 | info | connect
boschindego.0 | 2022-04-29 16:57:25.631 | info | connect ok
boschindego.0 | 2022-04-29 16:57:25.242 | info | connect
boschindego.0 | 2022-04-29 16:57:15.127 | error | connection error - credentials wrong or no network?
boschindego.0 | 2022-04-29 16:57:12.074 | info | connect
boschindego.0 | 2022-04-29 16:57:08.948 | info | connect ok
boschindego.0 | 2022-04-29 16:57:08.624 | info | connect
boschindego.0 | 2022-04-29 16:57:05.547 | info | connect ok
boschindego.0 | 2022-04-29 16:57:05.206 | info | connect
boschindego.0 | 2022-04-29 16:57:05.191 | info | starting. Version 0.9.16 (non-npm: a1development/ioBroker.boschindego#1d195f0e302f01e2eaf20eb6e4d6384dd547eed4) in /opt/iobroker/node_modules/iobroker.boschindego, node: v14.19.1, js-controller: 4.0.21

`

**Comment by a1development** [comment]
Ich konnte es mittlerweile bei mir selber auch nachvollziehen. Bis gestern lief der Adapter ohne die beschriebenen Probleme bei mir. Es wurde von Bosch was an der API geändert. Das habe ich gerade angepasst und in der aktuellen Version 0.9.17 korrigiert. 
Ich konnte mit der Version davor überhaupt keine Verbindung mehr aufbauen.
