### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by hugo419752** [a1development/ioBroker.boschindego#116]
Hi,

since a few days I get every 20 seconds the following error messages in the logfiles:

Quelle|                                                 Zeit | debug | Nachricht
boschindego.0 | 2022-05-12 12:22:11.344 | error | connection error - credentials wrong or no network?
boschindego.0 | 2022-05-12 12:22:11.161 | info | connect

I already restarted the instance, and the mower.

Is there anything I can do?

Thanks in advance.

**Comment by a1development** [comment]
I just uploaded a new version 0.9.17. Please uninstall and install the new version.

**Comment by hugo419752** [comment]
Where have you uploaded 0.9.17? Can't fid the new update.

**Comment by a1development** [comment]
You have to uninstall and manually install it from this repo. The same way you installed it the first time ( github -  user defined  )
