### ISSUE TITLE
Adapter terminated immer wieder

### ISSUE THREAD

**Issue by dominikkerkow** [a1development/ioBroker.boschindego#117]
Mit dem Update funktioniert der Adapter wieder, allerdings kommt zu manchen Zeiten nachfolgender Fehler. Manuell neu starten funktioniert. Dann habe ich wieder ca. eine halbe Stunde Ruhe.

`
boschindego.0 | 2022-05-17 12:15:49.786 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
boschindego.0 | 2022-05-17 12:15:49.785 | info | terminating
boschindego.0 | 2022-05-17 12:15:49.780 | error | Exception-Code: ERR_BAD_REQUEST: Request failed with status code 429
boschindego.0 | 2022-05-17 12:15:49.780 | error | unhandled promise rejection: Request failed with status code 429
boschindego.0 | 2022-05-17 12:15:49.779 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
boschindego.0 | 2022-05-17 12:15:49.778 | error | error in alerts request: AxiosError: Request failed with status code 429

`

**Comment by a1development** [comment]
Wie betreibst du den Adapter? 
Rufst du Funktionen wie z.b. refresh_state order clear_alerts etc selber auf bzw lässt das über ein von dir geschriebenen Script aufrufen?

**Comment by a1development** [comment]
Das ist echt merkwürdig. 429 ist eine Antwort von dem Service von Bosch das das Verbindungslimit überschritten ist. Irgendwas läuft da in deinem Fall nicht rund. Bei mir läuft das ohne einen einzigen 429 durch. Ich hatte sowas schon mal in Verbindung mit nicht so stabilen Internetverbindungen gesehen ( da reihen sich dann die Anfragen auf und wenn dann wieder eine Verbindung da ist, werden die alle abgefeuert). Sowas bekommt man meistens auch nicht wirklich mit. Ist der ioBroker evtl über Wlan angebunden? Gibt es evtl andere Probleme mit der Internetverbindung. 
Kommen diese Fehler nur, wenn der Bot unterwegs ist?

**Comment by a1development** [comment]
Hmm .. das könnte es evtl schon sein. Habe ich natürlich in dem Setup nicht getestet. Es wäre auf jeden Fall interessant wenn du das mal testen könntest, dann könnten wir das eingrenzen. Schalte doch mal einen von den beiden Adaptern aus und beobachte das mal für einen Tag. 
Startest du die Mäher selber? Oder lässt du das von SmartMow steuern?

**Comment by dominikkerkow** [comment]
Danke für die Infos und Gedanken.
Theoretisch sollte die zweifache Art und Weise nichts ausmachen, wenn die Adapter Limitierung an einem User hängt. Ich frage ja mit unterschiedlichen Accounts ab.
Generell fahre ich aktuell per Smart Plan und ggf. manuell per Button > API Befehl zusätzlich. Letztes Jahr habe ich eine eigene Programmierung zur Steuerung, mit kompletter Wetterabhängigkeit bei mir vor Ort geschrieben und somit beide über Deinen Adapter mit meiner Automation betrieben. Die Smart Funktion weicht extrem voneinander ab, selbst am gleichen Ort. Gerne würde ich meine Automation wieder nutzen, ist aber in diesem Jahr deaktiviert.

Ich versuche mal nur einen Adapter am Laufen zu haben und melde mich sonst wieder.

**Comment by a1development** [comment]
Ja melde dich so oder so mal was dein Test ergeben hat. Selbst wenn es dann mit einem Bot läuft, könnten wir evtl bei dir etwas tweaken, sodass weniger anfragen laufen. Das könntest du auch recht einfach testen wenn du bei dir  eine kleine Änderung im Code vornimmst .. aber dazu sollten wir erstmal deinen Test abwarten.

**Comment by bmause** [comment]
Guten Morgen, 
vielleicht kann mir jemand helfen, ich bekomme den Adapter (0.9.16)nicht zum laufen.
Habe schon mehrmals den Adapter gelöscht und neu installiert.
Bekomme immer diese Meldung ! 
Zugangsdaten sind korrekt eingeben. Emailadresse & Passwort. (mehrmals geprüft)

**31494 | 2022-05-20 08:39:11.698 | error | connection error - credentials wrong or no network?
-- | -- | -- | --
boschindego.0 | 31494 | 2022-05-20 08:39:11.543 | info | connect
boschindego.0 | 31494 | 2022-05-20 08:38:51.561 | error | connection error - credentials wrong or no network?**

**Comment by a1development** [comment]
@bmause die aktuelle Version des Adapters ist 0.9.17, der genau diese Verbindungsprobleme behoben hat. 
Du musst den Adapter deinstallieren, danach über "die Katze" -> Beliebige Quelle "https://github.com/a1development/ioBroker.boschindego" den Adapter neu laden und dann installieren.

**Comment by bmause** [comment]
> @bmause die aktuelle Version des Adapters ist 0.9.17, der genau diese Verbindungsprobleme behoben hat.
> Du musst den Adapter deinstallieren, danach über "die Katze" -> Beliebige Quelle "https://github.com/a1development/ioBroker.boschindego" den Adapter neu laden und dann installieren.

Danke funktioniert wieder :-)

**Comment by bmause** [comment]
Hmm, der Adapter ist online, aber es kommen nicht wirklich die Status Meldungen, 
Unter Map ist nichts mehr eingetragen 
Operation Data ist alles NULL

jemand eine Idee?

**Comment by a1development** [comment]
Status 504 ist ein Timeout. Bedeutet. Deine Anfrage wurde nicht vom Server beantwortet. 
Das kann verschiedene Gründe haben. Z.b. könnte die Gegenseite gerade nicht erreichbar sein. Oder es könnte auch ein Problem mit deiner Internetverbindung geben. 

Die Kartendaten etc werden erst geschrieben, sobald der Mäher gefahren ist. 

Ich habe es gerade für dich nochmal bei mir getestet. Da werden die Anfragen normal beantwortet. Falls es bei dir noch bestehen sollte, würde ich von einem Netzwerkproblem bei dir ausgehen?

**Comment by dominikkerkow** [comment]
@a1development habe nun beobachtet. Sobald ein Fehler auftritt, terminiert der Adapter.
Nun habe ich meine ganze Programmierung überprüft, zur Erklärung, ich baue mir alles selbst mit JS zusammen, auch alle Screens etc. Nun hatte ich bei auftretenden Status-Änderungen alles vom Bosch abgefragt, was dann im dümmsten Falle zu sehr vielen Abfragen in der Sekunde geführt hatte.
Nun habe ich weitere Datenpunkte eingerichtet und kann mir daher immer nur gezielt was aktualisieren. Damit sollte ich Abfragen an die API auf ein Minimum reduzieren. Ich teste nun und melde mich sonst wieder.

**Comment by bmause** [comment]
> @a1development habe nun beobachtet. Sobald ein Fehler auftritt, terminiert der Adapter.
> Nun habe ich meine ganze Programmierung überprüft, zur Erklärung, ich baue mir alles selbst mit JS zusammen, auch alle Screens etc. Nun hatte ich bei auftretenden Status-Änderungen alles vom Bosch abgefragt, was dann im dümmsten Falle zu sehr vielen Abfragen in der Sekunde geführt hatte.
> Nun habe ich weitere Datenpunkte eingerichtet und kann mir daher immer nur gezielt was aktualisieren. Damit sollte ich Abfragen an die API auf ein Minimum reduzieren. Ich teste nun und melde mich sonst wieder.

ok, wenn es eine neuere Version gibt, werde ich sie mal versuchen

**Comment by dominikkerkow** [comment]
Aktuell beendet sich der Adapter immer wieder.
Ich sehe auch ständig Connect Meldungen im Log, nachfolgend mal einen Auszug. Das geschieht offensichtlich zu oft, oder?

`

2022-06-08 16:05:44.662 | info | connect ok
-- | -- | --
boschindego.1 | 2022-06-08 16:05:44.287 | info | connect
boschindego.1 | 2022-06-08 16:05:44.662 | info | connect ok
boschindego.1 | 2022-06-08 16:05:44.287 | info | connect
boschindego.1 | 2022-06-08 16:05:44.662 | info | connect ok
boschindego.1 | 2022-06-08 16:05:44.287 | info | connect
boschindego.1 | 2022-06-08 15:50:43.643 | info | connect ok
boschindego.1 | 2022-06-08 15:50:43.284 | info | connect
boschindego.1 | 2022-06-08 15:35:42.444 | info | connect ok
boschindego.1 | 2022-06-08 15:35:42.103 | info | connect
boschindego.1 | 2022-06-08 15:20:41.553 | info | connect ok
boschindego.1 | 2022-06-08 15:20:41.101 | info | connect

`

**Comment by a1development** [comment]
@dominikkerkow da scheint mir was zu viel zu sein. Warum wird da 6x in einer Sekunde etwas aufgerufen? Der Adapter von sich aus sollte das nicht tun, außer du löst diese Funktion irgendwie aus. Vielleicht wird da etwas in deiner Vis getriggert was das auslöst? Nimm das doch mal zu Testzwecken da komplett raus für ein paar Tage und schau dir an ob es sich dann ändert. 
Das da "Connect" steht ist normal. Da wird dann die Verbindung erneuert. 
Echt merkwürdig. Bei mir läuft der Adapter einfach durch, ohne Probleme.

**Comment by dominikkerkow** [comment]
@a1development 
Nun habe ich den Adapter "auf frischer Tat" ertappt und endlich mal was im Log. Siehe Bild anbei. Vielleicht hilft dies bei der Fehleranalyse
![Bildschirmfoto 2022-07-06 um 17 07 39](https://user-images.githubusercontent.com/49316318/177697673-7140a204-3a6d-476a-8c9e-de28490639ef.png)
.

**Comment by a1development** [comment]
@dominikkerkow da tauchen halt immer wieder die 429 Fehlermeldungen auf, die von dem Bosch Service zurück gegeben werden.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429
"Too many requests" 
Ob das jetzt damit zutun hast, das du 2 Instanzen laufen hast, oder ob du evtl etwas triggerst, das da zu viele Anfragen gesendet werden. Aber der Service scheint nicht happy über deine Anfragen zu sein. 
Ich kann das leider bei mir nicht nachvollziehen.
Merkwürdig ist auch die "Wrong credentials or no network" Da scheint es vermutlich tatsächlich Verbindungsprobleme zu geben. Vielleicht "stauen" sich da auch Anfragen auf, die wegen Netzwerkproblemen nicht direkt durch laufen, und sobald es wieder läuft prasseln die alle auf einen Schlag auf den Service ein, was dann auch zu einem 429 führen könnte. Du meintest ja das dein ioBroker mit Lan Kabel dran ist, was eigentlich dagegen spricht, oder es gibt ein anderes Netzwerkproblem / Internet Problem ... aber aktuell tappe ich bei dir leider auch im dunklen. 
Wenn ich es debuggen müsste, würde ich einen Adapter löschen, den anderen Adapter aus der Vis schmeißen.. und das mal 1 -  2 Wochen laufen lassen. Dann kannst du die evtl Probleme durch Vis triggern von Buttons und durch 2 Adapter ausschließen. 
Dann bleibt eigentlich nur noch das Netzwerk, wenn es dann noch immer Auftritt. Wenn nicht, kannst du ja eins von beiden wieder rein nehmen und dann weiter schauen um langsam an den Punkt zu kommen wo du es eingrenzen kannst. 
Sorry das ich nicht wirklich gut helfen kann in dem Fall

**Comment by dominikkerkow** [comment]
@a1development 
Danke für die ausführliche Rückmeldung.
Noch eine letzte Frage dazu, dann gerne das Ticket schließen.
Mit welchen Aktionen erreiche ich im Adapter, dass dieser eine Kommunikation zur Bosch API öffnet / aktiviert? Doch nur bei den Befehlen zum Mähen, Löschen der Fehlermeldungen, etc.?

**Comment by a1development** [comment]
Eine Kommunikation zum Service wird bei allen commands aufgebaut ( go_home, mow, pause, refresh_state, clear_alerts ). 
Dazu kommt dann das wenn die Angabe "automatic_state_refresh" auf true steht, der Adapter je nach Status des Mähers in verschiedenen Abständen den Status abfragt. Während des Mähens regelmäßiger, außerhalb vom mähen weniger häufig.

**Comment by dominikkerkow** [comment]
Vielen Dank für die tolle Unterstützung!
