### ISSUE TITLE
Adapter is not working any more

### ISSUE THREAD

**Issue by jk-andersen** [a1development/ioBroker.boschindego#129]
Looks like Bosch did some work on the backend.

`<html>
<body>

boschindego.0 | 2022-07-31 09:51:17.649 | error | connection error - credentials wrong or no network?
-- | -- | -- | --
boschindego.0 | 2022-07-31 09:51:17.377 | info | connect
boschindego.0 | 2022-07-31 09:51:17.358 | info | starting. Version 0.9.16 in /opt/iobroker/node_modules/iobroker.boschindego, node: v16.16.0, js-controller: 4.0.23

</body>
</html>`

**Comment by a1development** [comment]
Just tested it with my mower. It works fine. The Adapter is connected, and it is responding to commands etc. 
This message is not very specific, something with the communication to the services does not work while connecting. So it could be a network issue on your site, it could be, that the service is not responding for your account ... This happens from time to time. 
In my case / test right now it works fine.

**Comment by jk-andersen** [comment]
You are right. I think my nodejs update killed it. I did a complete reinstall and pull from Github - Works fine now again.
