### ISSUE TITLE
Voltage state not correct

### ISSUE THREAD

**Issue by Scotty-89** [a1development/ioBroker.boschindego#37]
first of all thank you for the Adapter ! 

i found one "Bug" the "Voltage" show the same as "percent"

![image](https://user-images.githubusercontent.com/54929714/130511728-815683fa-e915-4055-918a-1962decb04c4.png)

i would expect for an 18V Lipo  at 100% Charge stage something around 21V (around 4.2V * 5 cells) 
can you check this please.

**Comment by a1development** [comment]
That are the values that the adapter receives from the service. As war as i understand, the voltages was used for the first generation of movers, later they introduced the percentage. So just ignore voltage in your case.
