### ISSUE TITLE
Indego 400 geht offline im SmartMoving, nach drücken des grünen Hakens startet er neu. 

### ISSUE THREAD

**Issue by Rette70** [a1development/ioBroker.boschindego#45]
**Describe the bug**  
Indego 400 geht offline im Smartmoving Modus, nach drücken des grünen Hakens startet er neu. 
**To Reproduce**  
wenn SmartMowing eingestellt ist, stürtzt er einmal am Tag ab.
Nach drücken des grünen Hakens startet er neu. Es kommt ganz oft keine Verbindung zustande.
Wenn er ausgeschaltet wird und wieder ein, geht es wieder ein paar Stunden. 
App-Software: 3.2.1
Indego Software: * 27357.01251 *
Node.jsv12.22.1, NPM 6.14.8

**Versions:**  
 - Adapter version: <0.9.10>
 - JS-Controller version: <v12.22.1> 
 - Node version: <6.14.8> 
 - Operating system: <Io-broker -Raspi>

**Comment by a1development** [comment]
Please try latest version 0.9.17 or higher
