### ISSUE TITLE
Falsche Werte in Datenpunkten

### ISSUE THREAD

**Issue by BramTown** [a1development/ioBroker.boschindego#6]
Seit der Admin v5.x wird kritischer geprüft ob das eingestellte Format eines Datenpunktes mit dem Inhalt übereinstimmt. Falls nicht, erfolgt eine entsprechende Meldung.

Die nachfolgenden Meldungen habe ich nun vom boschindego Adapter erhalten und müssten im Adapter korrigiert werden.

`

boschindego.0 | 2021-05-18 12:21:01.756 | info | (31096) State value to set for "boschindego.0.machine.alm_sn" has to be type "number" but received type "string"
-- | -- | -- | --
boschindego.0 | 2021-05-18 12:21:00.111 | info | (31096) State value to set for "boschindego.0.map.mapSVG" has to be type "number" but received type "string"
boschindego.0 | 2021-05-18 12:20:53.857 | info | (31096) State value to set for "boschindego.0.map.mapSVGwithIndego" has to be type "number" but received type "string"

`

**Comment by a1development** [comment]
in Version 0.9.11 korrigiert
