### ISSUE TITLE
Bosch Indego 1100: Verbunden, aber kann nicht gestartet werden

### ISSUE THREAD

**Issue by al10b** [a1development/ioBroker.boschindego#8]
**Problem:**  
Ich habe den boschindego-Adapter von Github installiert und die Account-Infos eingegeben. Die Instanz verbindet sich (grün) und nach ein paar Sekunden erscheinen die Objekte in ioBroker. Aber wenn ich versuche, den Roboter in ioBroker zu starten, passiert nichts.

Ich setze z.B. in ioBroker die Variable boschindego.0.commands.mov auf "true" und erwarte, dass der Roboter nach etwa 1 Minute losläuft, aber das tut er nicht.

Hier habe ich die Instanz auf Debug gesetzt und neu gestartet:

```
boschindego.0   2021-06-16 11:09:33.806 info    (26613) bot stopped
boschindego.0   2021-06-16 11:09:33.412 info    (26613) connect ok
boschindego.0   2021-06-16 11:09:33.027 info    (26613) connect
boschindego.0   2021-06-16 11:09:32.994 info    (26613) starting. Version 0.9.10 in /opt/iobroker/node_modules/iobroker.boschindego, node: v12.22.1, js-controller: 3.2.16
```

Hier setze ich boschindego.0.commands.mov auf true:

```
boschindego.0   2021-06-16 11:12:14.346 info    (26613) mow command sent
boschindego.0   2021-06-16 11:12:14.344 info    (26613) state boschindego.0.commands.mow changed: true (ack = false)

```
... aber nichts passiert.

Was mir außerdem auffällt: Wenn ich den Roboter manuell am Bedienpanel starte werden in boschindego.0.state nicht _alle_ Werte aktualisiert. Z.B bleibt der state immer auf 258 (Docked) und die xy-Positionen bleiben auch immer dieselben. Die Variablen mapsvgcache_ts dagegen wird aktualisiert.

Ein paar Versionsnummern:

iobroker    3.2.16
boschindego 0.9.10
node.js     v12.22.1
npm         6.14.12

Das Ganze läuft auf einem Raspberry Pi Modell 4B, den in monatlich aktualisiere.

Inzwischen habe ich den Adapter einmal komplett deinstalliert und neu installiert mit demselben Ergebnis.

Ich würde mich sehr über Unterstützung freuen.

**Comment by a1development** [comment]
OK danke für die detaillierte Beschreibung. Ich kenne jemanden der auch mit einem 1100 unterwegs ist und dort läuft der Adapter. Also sollte es kein generelles Problem mit dem Model sein. 
Nur um auf Nummer sichere zu gehen. Hast du mal Versucht den Bot nicht über das Bedientfeld sondern über die App auf deinem Handy zu starten? 
Ich hatte bei mir selber schon das Problem, das man zwar den "mow" command senden kann, aber der Bot das einfach nicht annimmt, weil gerade etwas nicht passt ( zu kalt / zu warm etc *g ) 
Wenn das mit der App erfolgreich Funktioniert, dann direkt nochmal mit dem Adapter bitte testen: Dann haben wir zumindest diese Fehlerquellen schon mal ausgeschlossen.

**Comment by al10b** [comment]
Tja, was soll ich sagen. Tatsächlich ist in der App der Roboter offline.

Zu meiner Ehrenrettung: Ich habe vor ioBroker den Roboter aus FHEM heraus gesteuert und dabei festgestellt, dass es mir das Bosch-Account lockt, wenn ich sowohl FHEM als auch die App mit der Bosch-Seite verbinde. Also habe ich dann die App nie mehr benutzt.

Jetzt muss ich erst mal sehen, ob mein Account wieder gelockt ist und wie ich ihn dann wieder entsperren kann. Der First-Level bei Bosch konnte mir nicht helfen, aber das ist eine andere Geschichte...

Ich melde mich, wenn ich da mehr erreicht habe.

**Comment by a1development** [comment]
Ok. Hatte sowas schon vermutet. Hast du das bei FHEM gestoppt?
Wenn das nicht parallel läuft könnte das eigentlich gehen?
Evtl mal ein bisschen warten und alles aus lassen bevor du das dann erstmal mit der App wieder testet.
Wenn die läuft, müsste eigentlich auch der Adapter wieder gehen.

**Comment by al10b** [comment]
Ich habe den ioBroker-Adapter deaktiviert und den Bosch-Support angemailt mit der Bitte, mein Account zurückzusetzen. Ich lass das jetzt erst einmal so, bis die App wieder funktioniert. Dann werde ich die App vom Telefon deinstalllieren (damit sie nicht dazwischenfunkt) und es noch einmal mit Deinem Adapter probieren. BTW: Wenn's funzt, herzlichen Dank!

PS: Auf FHEM läuft da nichts mehr.

**Comment by a1development** [comment]
@al10b Was du mal probieren könntest wegen deines "Offline" Problems. Ich hatte mal was ähnliches. Selber hab ich da die üblichen Sachen probiert. Mäher aus / an, Station ausgesteckt. App deinstalliert etc. 
Als ich mit dem Support gesprochen habe hat er mir folgende Reihenfolge genannt, die dann auch das Problem gelöst hat. 
1. Netzteil der Station für 10 Minuten! ausstecken
2. Mäher ausschalten und ein Stückchen aus der Station ziehen
3. App deinstallieren / neu installieren ( müsste man mal probieren ob es auch ohne geht :) )
4. Bot außerhalb! der Station einschalten
5. Bot in die Station an die Kontakte schieben und warten bis auf dem Display wieder Empfang angezeigt wird.

Das hat bei mir dann tatsächlich funktioniert.

**Comment by al10b** [comment]
Ich hätt's ehrlich gesagt nicht gedacht, aber das scheint tatsächlich geklappt zu haben. Der Roboter ist wieder online nachdem ich die beschriebene Prozedur durchgeführt habe (außer 4. - das geht bei mir nicht. Wenn ich den Roboter mit dem Schlüssel einschalte, bleibt das Display dunkel bis er angedockt ist).

Jetzt spinnt der Roboter anders: Startet und fährt gleich wieder zurück zur Basis und das immer so weiter...

Ich werde morgen mal meine Skripte überprüfen und es ggf. noch einmal mit der App versuchen.

Auf jeden Fall erst einmal: Danke! Dieses Ticket kann geschlossen werden.
